import React from 'react';
import Navbar from '../components/Navbar';
import { Target, Eye, ShieldCheck, Users } from 'lucide-react';

const AboutPage = () => {
  return (
    <div className="min-h-screen bg-gray-50">
      <Navbar />

      {/* 1. Header / Intro */}
      <section className="bg-orange-600 text-white py-20 px-4 text-center">
        <div className="max-w-4xl mx-auto">
          <h1 className="text-4xl md:text-6xl font-bold mb-6">Empowering Bharat's Artisans</h1>
          <p className="text-xl opacity-90">
            Swadeshi is more than a platform; it's a movement to bridge the gap between traditional Indian craftsmanship and conscious global travelers.
          </p>
        </div>
      </section>

      {/* 2. Mission & Vision */}
      <section className="py-16 px-4 max-w-6xl mx-auto grid md:grid-cols-2 gap-8">
        <div className="bg-white p-8 rounded-2xl shadow-sm border border-orange-100 flex flex-col items-center text-center">
          <Target className="w-12 h-12 text-orange-500 mb-4" />
          <h2 className="text-2xl font-bold text-gray-800 mb-4">Our Mission</h2>
          <p className="text-gray-600">
            To eliminate the middleman and ensure that 90% of the economic value generated by cultural tourism goes directly into the hands of rural artisans and homestay hosts.
          </p>
        </div>
        
        <div className="bg-white p-8 rounded-2xl shadow-sm border border-orange-100 flex flex-col items-center text-center">
          <Eye className="w-12 h-12 text-orange-500 mb-4" />
          <h2 className="text-2xl font-bold text-gray-800 mb-4">Our Vision</h2>
          <p className="text-gray-600">
            To make authentic, experiential "Phygital" tourism the standard, preserving India's dying arts by making them economically viable for the next generation.
          </p>
        </div>
      </section>

      {/* 3. Why Us? */}
      <section className="bg-white py-16 px-4">
        <div className="max-w-6xl mx-auto text-center">
          <h2 className="text-3xl font-bold text-gray-900 mb-10">Why Choose Swadeshi?</h2>
          <div className="grid md:grid-cols-3 gap-8">
            <div>
              <ShieldCheck className="w-10 h-10 text-orange-500 mx-auto mb-4" />
              <h3 className="font-bold text-xl mb-2">Verified Authenticity</h3>
              <p className="text-gray-600 text-sm">Every artisan and homestay is vetted. Our Digital Passport guarantees your experience is 100% genuine.</p>
            </div>
            <div>
              <Users className="w-10 h-10 text-orange-500 mx-auto mb-4" />
              <h3 className="font-bold text-xl mb-2">Direct Connection</h3>
              <p className="text-gray-600 text-sm">No agencies. No hidden fees. You book directly with the creators and hosts.</p>
            </div>
            <div>
              <Target className="w-10 h-10 text-orange-500 mx-auto mb-4" />
              <h3 className="font-bold text-xl mb-2">Cultural Preservation</h3>
              <p className="text-gray-600 text-sm">Your booking directly funds the continuation of centuries-old artistic traditions.</p>
            </div>
          </div>
        </div>
      </section>

      {/* 4. Team & BOD */}
      <section className="py-16 px-4 max-w-6xl mx-auto text-center">
        <h2 className="text-3xl font-bold text-gray-900 mb-4">The Team Behind Swadeshi</h2>
        <p className="text-gray-600 mb-10">Team Avengers - Building for Atmanirbhar Bharat</p>
        
        <div className="grid grid-cols-2 md:grid-cols-4 gap-6">
          {/* Team Members */}
          {['Ketki Salunkhe', 'Ajinkya Funde', 'Anshuman Sugandhi', 'Farhan Ansari'].map((name, i) => (
            <div key={i} className="bg-white p-6 rounded-xl shadow-sm border border-gray-100">
              <div className="w-20 h-20 bg-orange-100 rounded-full mx-auto mb-4 flex items-center justify-center text-orange-600 font-bold text-xl">
                {name.charAt(0)}
              </div>
              <h3 className="font-bold text-gray-800">{name}</h3>
              <p className="text-xs text-orange-600 mt-1">{i === 0 ? 'Team Leader' : 'Member'}</p>
            </div>
          ))}
        </div>
      </section>

    </div>
  );
};

export default AboutPage;